name: Deploy to TestFlight

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  testflight:
    runs-on: macos-13
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build extension assets
      run: npm run build
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        
    - name: Download Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: xyz.foo.bar123
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
        
    - name: Download Extension Provisioning Profile
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: xyz.foo.bar123.Extension
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
        
    - name: Build Archive
      run: |
        xcodebuild \
          -project bar123.xcodeproj \
          -scheme bar123 \
          -destination generic/platform=iOS \
          -archivePath $RUNNER_TEMP/bar123.xcarchive \
          archive \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER="xyz.foo.bar123" \
          CODE_SIGN_IDENTITY="iPhone Distribution"
          
    - name: Export IPA
      env:
        EXPORT_OPTIONS_PLIST: ${{ runner.temp }}/ExportOptions.plist
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>destination</key>
          <string>upload</string>
          <key>method</key>
          <string>app-store</string>
          <key>teamID</key>
          <string>2858MX5336</string>
          <key>uploadBitcode</key>
          <false/>
          <key>uploadSymbols</key>
          <true/>
          <key>compileBitcode</key>
          <false/>
        </dict>
        </plist>' > $EXPORT_OPTIONS_PLIST
        
        xcodebuild \
          -exportArchive \
          -archivePath $RUNNER_TEMP/bar123.xcarchive \
          -exportOptionsPlist $EXPORT_OPTIONS_PLIST \
          -exportPath $RUNNER_TEMP/build
          
    - name: Upload to TestFlight
      uses: Apple-Actions/upload-testflight-build@v1
      with:
        app-path: '${{ runner.temp }}/build/bar123.ipa'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}